job/urls.py
from django.urls import include, path

from . import views
from . import api

app_name = 'job'

urlpatterns = [
    path('fav/<str:slug>', views.post_fav, name='a'),
    path('favourite', views.post_favourite_list, name='post_favourite_list'),
    path('your/apply',views.Apply_view,name='Apply_view'),
    path('apply',views.Apply_view_2,name='Apply_view_2'),
    path('', views.job_list, name='job_list'),
    path('add', views.add_job, name='add_job'),
    path('<str:slug>', views.job_detail, name='job_detail'),
    path('delete/<str:slug>', views.delete_job, name='delete_job'),
    path('api/jobs', api.job_list_api, name='job_list_api'),
    path('api/jobs/<int:id>', api.job_detail_api, name='job_detail_api'),
    path('api/v2/jobs', api.JobListApi.as_view(), name='job_list_api'),
    path('api/v2/jobs/<int:id>', api.JobDetail.as_view(), name='job_detail_api'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls',namespace='jobs')),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls'))


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
import django_filters
from django_countries.fields import CountryField

# Create your models here.


JOB_TYPE = (
    ('Full Time', 'Full Time'),
    ('Part Time', 'Part Time'),
)


def image_upload(instance, filename):
    imagename, extension = filename.split(".")
    return "jobs/%s.%s" % (instance.id, extension)


class Job(models.Model):
    owner = models.ForeignKey(User, related_name='job_owner', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    location = CountryField()
    job_type = models.CharField(max_length=15, choices=JOB_TYPE)
    description = models.TextField(max_length=1000)
    emails = models.EmailField(blank=True, null=True)
    published_at = models.DateTimeField(auto_now=True)
    Vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload, blank=True, null=True)
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title)
        super(Job, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('jobs:job_detail', args=[str(self.id)])

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Apply(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, related_name='apply_job', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/', blank=True, null=True)
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Apply, self).save(*args, **kwargs)

    def __str__(self):
        return self.name





































'''
السلام عليكم كابتن
بس اريد احجي وياك بموضوع
كابتن انا اخر 5 لعبات لعبت بس 3 دقايق
ف اريد اعرف شلون انت تعرف وتقيم مستوايه اذا انا لاعب بس 3 دقايق اخر 5 لعبات؟؟
اذا تقيمو بالتمارين الي ناخذها ف انا كل التمارين دا اسويه بس كم تمرين ما اقدرله
قصدي ع تمارين القوة واللياقة
انا مو علمود اريد العب وهاهيه. ومدا اكول انا خوش لاعب
 انا اريدك تنطيني فرصة تشوف بيها مستوايه زين لا ؟


كابتن انا احس محد مهتم بيه لا بالتمرين ولا بالعبة
مثلا ولا مرة بالتمرين احد كايلي هاي غلط , هاي صح
عكس بقية اللواعيب توكف ع راسهم بس تريدهم يطبقون تشجعهم تحجي وياهم تكلهم هاي خطأ تصححلهم بينما انا محد دايرلي بال
ليش شنو فرقهم عني
حتى باللعبات من تلعبني اخر شي متباوع ولا تنتبه عليه يمكن انت تقول خطيه امير ملعبتها خل العبها يعني انت مرايدني لان محتاجني باللعبة مثلا. بس علمود العب ومن العب ماكو لا تكلي لعبت زين ولا تكلي لعب مو زين انا هاي اريدك اتكلياها
انا هاي مهامتني وعادي عندي بس داشوفك الفرق بيني وبينهم

يعني انا اريد من العب تكلي شنو اخطائي تكلي عندك هيج شي طوره
"مثل البقية"
هاي اذا انطيتني فرصة العب
انطيني فرصة وشوفني يمكن العب اسوء لعب ويمكن العب خوش لعب
كابتن انا من ارجع للبيت اكول ليش الكابتن مدخلني باللعبة شنو الي شافو عني ومخلاه يلعبنيي؟؟
كلي علمود افتهم واشتغل عليه
وارجع واكول انا ماهمني اللعب انا هامني انو انت تشوف مستوايه وتكلي اخطائي وين و(تهتم بيه مثل البقيه)
انا هذا الحجي صارلي فترة اريد احجيه بس مستحي منك
واسف اذا تجاوزت حدودي او حجيت شي خطأ
'''

job/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponsePermanentRedirect
from .models import Job, Apply
from django.core.paginator import Paginator
from .form import ApplyForm, JobForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .filter import JobFilter


# Create your views here.

def job_list(request):
    job_list = Job.objects.all()

    myfilter = JobFilter(request.GET, queryset=job_list)
    job_list = myfilter.qs

    paginator = Paginator(job_list, 4)  # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'jobs': page_obj, 'myfilter': myfilter, 'dd': job_list}  # template name
    return render(request, 'job/job_list.html', context)


def job_detail(request, slug):
    is_fav = False
    job_detail = Job.objects.get(slug=slug)


    if request.method == 'POST':
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.job = job_detail
            myform.save()


    else:
        form = ApplyForm()

    context = {'job': job_detail, 'form1': form, 'is_fav': is_fav}
    return render(request, 'job/job_detail.html', context)


def Apply_view(request):
    Apply_list = Apply.objects.filter(user=request.user).order_by('user')
    job_list = Job.objects.all()

    return render(request, 'job/exampl.html', {'Apply_list': Apply_list, 'dd': job_list})


def Apply_view_2(request):
    Apply_list = Apply.objects.all()

    return render(request, 'job/exampl_2.html', {'Apply_list': Apply_list})


def delete_job(request, slug):
    job = get_object_or_404(Job, slug=slug)
    if request.method == 'POST':
        form = JobForm(request.POST, instance=job)
        job.delete()
    else:
        form = JobForm(instance=job)
    return render(request, 'job/fav.html', {'formdel': form})


@login_required
def add_job(request):
    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save()
            return redirect(reverse('jobs:job_list'))


    else:
        form = JobForm()

    return render(request, 'job/add_job.html', {'form': form})


def post_favourite_list(request):
    user = request.user
    favourite_posts = user.favourite.all()
    context = {'favourite_posts': favourite_posts}
    return render(request, 'job/fil.html', context)


def post_fav(request, slug):
    post = Job.objects.get(slug=slug)
    if post.favourite.filter(id=request.user.id).exists():
        post.favourite.remove(request.user)
    else:
        post.favourite.add(request.user)
    return redirect(reverse('jobs:job_detail',kwargs={'slug':post.slug}))

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
 <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Post New Job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}

                                <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock body %}

job/templates/job/exampl.html
{% extends 'base.html' %}
{% block body %}

{% for one in Apply_list %}
 <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{one.job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Apply info</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Job Name: <span><a href="/jobs/?title={{one.job}}&location=&job_type=&description=&salary=&experience=&category=">{{one.job}}</a></span></li>
                                <div>
                                </div>
                            </ul>
                        </div>
                         <div class="p-5">
                    </div>

                    </div>


                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock body %}

job/templates/job/exampl_2.html
{% extends 'base.html' %}
{% block body %}

{% for one in Apply_list %}
 {% if request.user == one.job.owner %}
 <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{one.user}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Apply info</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>User Apply: <span>{{one.user}}</span></li>
                                <li>Job Name: <span>{{one.job}}</span></li>
                                <li>Job Email: <span>{{one.email}}</span></li>
                                <li>User Name: <span>{{one.name}}</span></li>
                                <li>website: <span><a href="{{one.website}}">{{one.website}}</a></span></li>
                                <li>Cv: <span>{{one.cv}}</span></li>
                                <li>cover letter: <span>{{one.cover_letter}}</span></li>
                                <li>Apply at: <span>{{one.created_at}}</span></li>
                                <div>

</div>

                            </ul>
                            <pre></pre>
                            <pre></pre>
                            <pre></pre>
                            <pre></pre>
                            <h4>to contact with him send Message to this Email  "{{one.email}}" </h4>
                        </div>
                         <div class="p-5">
                    </div>

                    </div>


                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

{% endfor %}

{% endblock body %}

job/templates/job/fav.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                        </div>
                                        <div class="location">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form formdel %}
                            {% buttons %}

                                <button class="boxed-btn3 w-100" type="submit">delete Now</button>
                            {% endbuttons %}

                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>

                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }

                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}

job/templates/job/fil.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Favorite Jobs</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->

    <div class="job_listing_area plus_padding">
        <div class="container">

                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Favorite Jobs</h4>
                                </div>
                                <div class="col-md-6">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
{% for job in favourite_posts %}
        <div class="col-lg-12 col-md-12">
            <div class="single_jobs white-bg d-flex justify-content-between">
                <div class="jobs_left d-flex align-items-center">
                    <div class="thumb">
                        <img src="" alt="">
                    </div>
                    <div class="jobs_conetent">
                        <a href="{% url 'jobs:job_detail' job.slug %}"><h4>{{job}}</h4></a>
                        <div class="links_locat d-flex align-items-center">
                            <div class="location">
                                <p> <i class="fa fa-map-marker"></i> {{job.location}}</p>
                            </div>
                            <div class="location">
                                <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="jobs_right">
                    <div class="apply_now">
                        <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                        <a href="{% url 'jobs:job_detail' job.slug %}" class="boxed-btn3">Apply Now</a>
                    </div>
                    <div class="date">
                        <p>Date line: {{job.published_at|date:'d M o'}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

                </div>
            </div>
        </div>
    </div>
{% endblock body %}

job/templates/job/job_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="img/svg_icon/1.svg" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{job.location}}</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    {% if request.user in job.favourite.all %}
                                    <a class="heart_mark" href="{% url 'jobs:a' job.slug %}"> <i class="fa fa-heart"></i> </a>

                                    {% else %}
                                    <a class="heart_mark" href="{% url 'jobs:a' job.slug %}"> <i class="ti-heart"></i> </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>
                    </div>
                    {% if request.user != job.owner %}

                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form1 %}
                            {% buttons %}

                                <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
                {% else %}
                <div class="apply_job_form white-bg">

                    </div>
                </div>
                {% endif %}
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published_at|date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.Vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.salary}}k/y</span></li>
                                <li>Location: <span>{{job.location}}</span></li>
                                <li>Job Nature: <span> {{job.job_type}}</span></li>
                                <li>Email: <span> {{job.emails}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }

                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>

                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock body %}
ايه يعني مفيش حل؟؟





السلام عليكم انا شغال جانغو فعامل حتة الadd to favouraite بيجيلي ده الايرور عملت كل حاجة حتى بدلت الid بslug ومش شغال المشكلة في الhtml هنا
<!--/  <a href="{% url 'jobs:a' job_detail.id %}">Add to Favourties</a> -->

ملحوظة : انا لمن بحط الid بتاعها تشتغل عادي مثلا كده

<!--/<a href="{% url 'jobs:a' 20 %}">Add toFavourties</a> -->
ارجو حل وشكرا